name: Complete CI workflow
on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calculator-app template
        uses: Coderslab-core/action-checkout-and-move@v1
        with:
          repository: PXL-2TIN-DevOps-Resources/calculator-app-finished
          dest-path: ./calculator-app
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install npm
        run: npm install
        working-directory: ./calculator-app
      - name: Run tests
        run: npm test
        working-directory: ./calculator-app
      - name: Run unit tests with coverage
        run: npm test -- --coverage
        working-directory: ./calculator-app
      - name: Code Coverage Report
        uses: mridang/action-test-reporter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: calculator-app/coverage/clover.xml
          working-directory: ./calculator-app


    
